### ISSUE TITLE
[BUG] Not possible to use env just as reference temperature

### ISSUE THREAD

**Issue by creatvty** [revk/ESP32-Faikin#174]
First of all, AWESOME device you made there and props for your active engagement in the project @revk 

**Daikin hardware**
FTXM35 

**Describe the bug** 
I would like to use an external reference temperature sensor without Faikin going into auto mode 

**To Reproduce**
So the use case I'm trying to realize is **just** to pass a reference temperature via MQTT (e.g. `env`) to Faikin which then uses this as a reference temperature instead of the internal temperature.

My first attempt was to pass this Payload
```
{
  "env": 20.4,
}
```

This is not accepted by Faikin. Only if I pass additionally a target with `env` the message is accepted by Faikin

```
{
  "env": 20.4,
  "target": [21, 21]
}
```
In this case though, Faikin launches into the "auto" mode without being able to prevent this. "No problem", I thought, "I just pass the target temp of the AC". After that it went into a feedback loop because Faikin would set the target state to like 32° which then would be picked up by the message again and would send MQTT messages like this:

```
{
  "env": 20.4,
  "target": [32, 32]
}
```
A workaround would be to not use the climate entity of Faikin at all and cobble it together from some helper entities. But this is not very satisfactory IMO.

**Expected behavior**
- 1 Just allow to only pass `env` as payload and use this as a reference temperature. Or allow to make the auto mode optional
- 2 When passing the `env` and `target` message,  use `env` for  `current_temperature` instead of internal temperature. And make it optional to **not** send the auto temperature back but the the middle between min and  max target temperature or something

I hope my request is clear enough. Thanks in advance

**Comment by revk** [comment]
What is the issue with auto mode?

There is a setting to stop out changing heat/cool in the Faikin auto mode, but you cannot actually override the internal temperature of the air-con, so the Faikin auto mode manages that by setting high or low targets in the aircon to reach what you set in the Faikin auto mode.

Does that make sense?

**Comment by creatvty** [comment]
I don't necessarily have an issue with auto mode. I just want to have the ability not to use it when I want to use a remote sensor. Why should that not be possible?

But IMO exposing the temperature that is set inside the AC while in Auto mode is unnecessarily low level. If it is in auto mode I don't need to know that internally Faikin sets the AC target temperature to 32°C. I want to know what the target is that was actually set. i.e. 21°C

**Comment by revk** [comment]
Well what do you think the remote sensor value would do?

As I say, we have no way to tell the aircon the remote value, all was can do is set temperature targets. We set high and low to achieve the target, it works.

You can change some settings to as how much higher or lower we set the target, if you wish, they are in the manual, honest...

**Comment by creatvty** [comment]
I see. I thought it was a native feature of the AC to allow a an external sensor. Like the one that is actually on the remote that is supplied with my AC at least. Is that not possible?

**Comment by revk** [comment]
Sadly not, it would be great if it did (and if someone finds an S21 message to do that I'll code it), but sadly not, sorry.

**Comment by creatvty** [comment]
Ah okay. Well here is to hoping it will be found some time. Unfortunately I have no experience in the protocol so I cannot contribute. 

So then my idea to improve usability would be to expose the high level values in MQTT that auto mode is going for. Which would be the `env` value fed back and something between min and max target. I assume there is a value like `current_target_value` or such.

![image](https://github.com/revk/ESP32-Faikin/assets/58488011/6d13b919-8044-435e-9c42-d9fb71dd42b1)

**Comment by revk** [comment]
It is definitely in MQTT but I thought we exposed to home assistant now anyway. I assume you are up to date.

**Comment by creatvty** [comment]
I updated yesterday. So should be. Here is my config
```
unique_id: xxx
device:
  identifiers:
    - xxx
  name: Faikin Livingroom
  sw_version: 96061bd
  manufacturer: RevK
  configuration_url: http://Faikin Livingroom.local/
icon: mdi:thermostat
min_temp: 16
max_temp: 32
temperature_unit: C
temperature_command_topic: command/Faikin Livingroom/temp
temperature_state_topic: xxx
temperature_state_template: '{{value_json.target}}'
current_temperature_topic: xxx
current_temperature_template: '{{value_json.temp}}'
mode_command_topic: command/Faikin Livingroom/mode
mode_state_topic: xxx
mode_state_template: '{{value_json.mode}}'
fan_mode_command_topic: command/Faikin Livingroom/fan
fan_mode_state_topic: xxx
fan_mode_state_template: '{{value_json.fan}}'
fan_modes:
  - auto
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - night
swing_mode_command_topic: command/Faikin Livingroom/swing
swing_mode_state_topic: xxx
swing_mode_state_template: '{{value_json.swing}}'
swing_modes:
  - 'off'
  - H
  - V
  - H+V
  - C
preset_mode_command_topic: command/Faikin Livingroom/preset
preset_mode_state_topic: xxx
preset_mode_value_template: '{{value_json.preset}}'
preset_modes:
  - eco
  - boost
  - home
platform: mqtt
```

This is the payload I receive:
![image](https://github.com/revk/ESP32-Faikin/assets/58488011/7ab533d8-3b1e-426e-bd80-886d2c4b0fec)

Don't see `env` there. On the other hand I do have the `env` value already since I send it via MQTT and also the target since I'm getting it from the `climate` entity of the AC. I would just like the climate entity to resemble what is actually happening. So that `current_temperature` shows the value of `env` and so on.
