### ISSUE TITLE
[FEATURE] HA integration: add Failkin restart button

### ISSUE THREAD

**Issue by macmpi** [revk/ESP32-Faikin#657]
**Daikin hardware**
any, but vested interest for FTXS20G2V1B or FVXS50FV1B / S21

**Is your feature request related to a problem? Please describe.**
Restarting Failkin device remotely is not easy for average user through MQTT cryptic command.

**Describe the solution you'd like**
A simple restart button on HA UI would be much more convenient.
This could be set within default MQTT integration as **MQTT button**.

**Describe alternatives you've considered**
Custom restart button can be constructed as HA template in `configuration.yaml` as per below: however this still requires user know-how.
Default integration would be much straightforward.
```
mqtt:
  - button:
      unique_id: button_faikin_restart_<faikin-name>
      command_topic: "command/<faikin-name>/restart"
      payload_press: ""
      device_class: "restart"
```

**Additional context**
see[ MQTT Button](https://www.home-assistant.io/integrations/button.mqtt/).
Note: `availability` option might be worth to set too.
(maybe reset to factory and firmware upgrades management could eventually have similar button)
